name: CHE1148_Defect_Detecting
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - pytorch-cuda=12.4
  - numpy
  - pandas
  - h5py
  - scikit-learn
  - matplotlib
  - seaborn
  - tqdm
  - ipykernel
  - pip
  - pip:
    - torchinfo
    - captum
